### ISSUE TITLE
Issue with ISE VM when passing user_data

### ISSUE THREAD

**Issue by stoveranger** [grg1bbs/Terraform_ISE_Azure_Deployment#1]
Hi - I have been trying to deploy an ISE VM for weeks now and for some reason they never seem to "complete" for me.  I'm able to deploy this through the Azure Portal without issue, but if I deploy a machine by Terraform using the same user_data, for some reason the machine never seems to work.  

I'm not sure if you have this issue, but the admin password never works for me, nor does the SSH key I create after the machine is deployed.  However, if I don't pass any user_data to the machine, I'm able to authenticate fine (but obviously the ISE stuff never comes online).  I've triple checked that the user_data parameters are all within reason, and like I said I used the same user_data on a machine created through the portal without issue.  The only way I'm able to get into the machine is if I change the password through the portal using the VM agent.

I've also noticed that the machine I deployed manually through the portal does not let me authenticate either, but after the ~30 minute wait, the admin page becomes accessible and I can proceed with the first time setup.  I'm not sure if this is by design or if something just isn't working right.

I'm at a loss for what to do here since I have literally used the files from your repo to deploy a test VM and I have the same issue.  I've also locked my provider to the same version you've mentioned, and I've tried both an Azure build agent and a windows build agent.  

For argument's sake, I deployed another random RHEL machine and passed user_data to it to see if I would encounter the same problem, but I am able to SSH into that machine without issue, so it seems specific to the ISE VM image.

Please let me know if you have any thoughts on this since I'm at a loss and plan on deploying through the portal for our environment :(.  Thanks for the help!

**Comment by grg1bbs** [comment]
Hi @stoveranger. The biggest issue I've seen with deploying using the VM variant is something in the user data content that the Zero Touch Provisioning (ZTP) process does not like. If the ZTP process fails, the application build process will fail.
Are you able to share a sanitised version of your user data content?

One of the biggest mistakes I've seen people make is using 'cisco' (including different case or reverse) in the password field. This does not meet the password requirements as per the [Cloud Deployment Guide](https://www.cisco.com/c/en/us/td/docs/security/ise/ISE_on_Cloud/b_ISEonCloud/m_ISEonAzureServices.html#task_f52_p2r_lsb) and will cause the ZTP process to fail.
With ISE 3.2, the initial GUI login will require a change of the default 'iseadmin' account password so I normally use something like 'Ch@ngePassw0rd' in my user data.

What kind of error are you getting when trying to connect via SSH using the 'iseadmin' username and private key?

**Comment by stoveranger** [comment]
Do we have any visibility into the ZTP logs?  I've been running into such strange behavior where it seems like regardless of what I pass to the user_data on the machine, it doesn't like it.  If I pass nothing, the actual Linux OS seems to work fine.  After one of my failed deployments, I actually reset the password using the Portal and I went into the iseadmin directory to find that it wasn't creating the .ssh/authorized_keys, so there was no way my keys would ever work, but if I don't pass any user_data to the machine, the SSH key provisioning works fine.  Same is true of password auth; if I enable it and set a password, it works fine unless I supply user_data, in which case it doesn't work at all.

Below is the user_data text file that I read in with filebase64 as you've shown with one of my more recent deployments.  I've also tried this with a templatefile and base64enoding just a plain heredoc string, but no dice.

```
hostname=ise321-az1
primarynameserver=10.222.10.111
dnsdomain=my.domain.com
ntpserver=10.202.10.155
timezone=UTC
password=1oQEv5Zo7n
ersapi=no
openapi=no
pxGrid=no
pxgrid_cloud=no
```

I've also tried adding `username=iseadmin`  (although I've noticed the Azure doc doesn't mention this specifically, but I have seen an example repo where this worked)

For the `admin_username` on the machine itself, I'm also using iseadmin.  I've made sure to set a password within the parameters of the Cisco doc as well, and it doesn't contain cisco or ise in any fashion.

I noticed you were using a newer provider version than me so I even tried changing that to no avail.

**Comment by aussietexan** [comment]
Hi @stoveranger. I spun up an ISE VM using my TF code and the same timezone and password values you are using. After waiting 30 minutes for the ISE application build to complete, I was able to SSH into the node using my private key and the username 'iseadmin' with no issues.
I am not aware of a way to monitor the ZTP process for public cloud deployments. When deploying an on-prem VMware node using the OVA, the ZTP logs can be seen using a virtual serial port, but that is not an option in the public cloud.

I don't believe using the password reset from the Azure portal will have any affect on the 'iseadmin' account password. The ISE nodes do not provide for root access without support from TAC, so I doubt that option is supported.

Are you using the same code in your resource block for the ISE VM that I have posted here?

It sounds like SSH is not working regardless of whether you are building the node from the Azure portal (VM variant process) or using Terraform, so you might want to open a TAC case to see if they can work with you to investigate the issue.

**Comment by stoveranger** [comment]
Sorry when I was saying iseadmin password reset, I was referring to the local admin on the machine, not the one intended for use within ISE - I had just started using iseadmin as the machine local admin as well.  

Yes I have used the same resource blocks as you've posted, just substituting my own host name and subnet ID, user data, no public ip. I've tried with and without an NSG (our subnets/vnets don't block any of the protocol traffic that you've built the rules for anyhow). I've tried with and without disable password auth. I'll be happy to share the code too. The only thing I haven't tried is deploying to another region; I've done all of this is in US Central, but the portal-initiated deployment works fine in the region so I doubt that's it.

**Comment by stoveranger** [comment]
Here is all the relevant code:
```
resource "tls_private_key" "isekey" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Create a network interface for the ISE node
resource "azurerm_network_interface" "ise32_az1_gig0" {
  name                = "ise32-az1-gig0"
  location            = var.location
  resource_group_name = module.vmtest_rg.rg_name

  ip_configuration {
    name                          = "ise32-az1-gig0"
    subnet_id                     = data.terraform_remote_state.spoke.outputs.sn00_id
    private_ip_address_allocation = "Dynamic"

  }
}


# Create ISE VM instance
resource "azurerm_linux_virtual_machine" "ise321_az1" {
  name                = "ise321-az1"
  resource_group_name = module.vmtest_rg.rg_name
  location            = var.location
  size                = "Standard_D8s_v4"
  admin_username      = "iseadmin"
  
  network_interface_ids = [azurerm_network_interface.ise32_az1_gig0.id]
  user_data             = filebase64("./ise32-az1.txt")

  admin_ssh_key {
    public_key = chomp(tls_private_key.isekey.public_key_openssh)  # I've tried this with and without the chomp
    username   = "iseadmin"
  }

  os_disk {
    caching              = "ReadWrite"
    disk_size_gb         = 300
    storage_account_type = "StandardSSD_LRS"
  }

  plan {
    name      = "cisco-ise_3_2"
    product   = "cisco-ise-virtual"
    publisher = "cisco"
  }

  source_image_reference {
    offer     = "cisco-ise-virtual"
    publisher = "cisco"
    sku       = "cisco-ise_3_2"
    version   = "3.2.0"  # I've tried latest here as well
  }
}

resource "azurerm_network_security_group" "ise_sg2" {
  name                = "nsg-isetest"
  location            = var.location
  resource_group_name = module.vmtest_rg.rg_name

  security_rule {
    name                       = "permit-ssh-all"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "permit-https-all"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "443"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "permit-onprem"
    priority                   = 120
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "10.0.0.0/8"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "permit-icmp"
    priority                   = 130
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Icmp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_network_interface_security_group_association" "ise_sg_assoc2" {
  network_interface_id      = azurerm_network_interface.ise32_az1_gig0.id
  network_security_group_id = azurerm_network_security_group.ise_sg2.id
}



ise32-az1.txt content:
hostname=ise321-az1
primarynameserver=10.222.10.111
dnsdomain=my.domain.com
ntpserver=10.202.10.155
timezone=UTC
password=1oQEv5Zo7n
ersapi=no
openapi=no
pxGrid=no
pxgrid_cloud=no
```
Sorry I know I'm repeating myself, but I have tried with and without the NSG, with and without the SSH keys (using password auth), but nothing seems to give.  I can build a machine from the portal using this exact same user_data, on the same subnet and resource group.  Let me know what you think.  Thanks a lot!

**Comment by stoveranger** [comment]
Here is a screen shot of what I encounter when I try to SSH into the machine using the key:
![image](https://user-images.githubusercontent.com/77512272/226911371-d42655c0-f370-4a00-978e-96364d9f6f4b.png)

And if I were to do a password reset and explore the file system, I would find that the .ssh/authorized_keys path was never created under iseadmin, so the public key that I tried to insert just goes into oblivion.  I'll stand up another machine with the same image and no user data and I'll be able to authenticate to it without issue.

**Comment by grg1bbs** [comment]
I tested with the same VM size you're using as well, but I cannot replicate any issue. The only thing I'm doing different is using an SSH private/public key that was created ahead of time from Azure rather than generating a new private key via the TF resource. I've done this so that I can spin the lab up and down and consistently use the same keypair for SSH.

I'm mainly connecting via SSH using the MacOS terminal, but I also copied my private key to a Windows VM, converted it to the .ppk format using PuTTYGen, and was able to connect using PuTTY.

You might try generating an SSH keypair in Azure and reference it locally in your TF code as I've done to see if that makes a difference.

**Comment by stoveranger** [comment]
Would any of the values in the user_data affect the build besides the password?  The VNet/Subnet I'm deploying on to can certainly reach everything in my environment, but I'm just wondering if it would choke if it didn't think it could communicate with the DNS server, the NTP server, or the domain suffix?  Are those values validated in some day during the build process?  

I know the article says they aren't validated when supplied, but I'm sure they can mess up the build process in some way.  The
only reason I'm asking is because I did just try to deploy this in my test tenant as well which cannot actually reach any of the values I'm putting for DNS, NTP or Domain Name, and I also could not SSH to it after it was built and I waited an hour.

**Comment by grg1bbs** [comment]
@stoveranger... No, there should be no issue with connectivity. I just spun up a new instance using private IP addresses for the DNS and NTP servers to which the node would have no connectivity or name resolution and I was able to SSH into the new instance after 30 minutes.

**Comment by stoveranger** [comment]
Well I'm perplexed then.  MSFT wants to investigate this with me further, so I'm going to deploy an ISE VM with and without user data for them to see.  Is there a way that I can re-trigger the ISE scripts/internal provisioning after the 30 minutes have come and gone and the machine doesn't work?  MSFT wanted to test incrementally adding user data to see if one of the values in particular are causing the machine to go sideways, but I wouldn't know how to re-run the ISE stuff without re-deploying the machine.

**Comment by grg1bbs** [comment]
No, there is no way I'm aware of to re-trigger the provisioning process. AFAIK, the Zero Touch Provisioning process only kicks off at the initial deployment. The same is true with a VM deployment via ISO in VMware.
